# Site settings
title: Ion Petrache's portofolio
description: The portofolio of Ion Petrache
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: https://ionutpetrache.github.io/

# User settings
username: Ion Petrache
user_description: Hi there,</br> I am Ion Petrache, a software engineer with focus on testing and code quality.</br> I help teams and organisations with implementation of testing strategies for their products.
user_title: Test Automation Engineer
email: ionpetrache@gmail.com
twitter_username: ionpetrache
github_username:  ionutpetrache
gplus_username:  ionpetrache

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
