# Site settings
title: Ion Petrache portofolio
description: The portofolio of Ion Petrache
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: https://ionutpetrache.github.io/

# User settings
username: Ion Petrache
user_description: Hi there,</br> I am Ion, a software engineer with focus on testing and code quality.</br> I help teams and organisations with implementation of testing automation strategies for their products.
user_title: Software Engineer in Test
email: ionpetrache@gmail.com
twitter_link: https://twitter.com/ionpetrache
github_link:  https://github.com/ionutpetrache
linkedin_link:  https://www.linkedin.com/in/ionpetrache
stackoverflow_link: https://stackoverflow.com/users/6434628/ionut
blog_link: https://automationengineeringblog.wordpress.com


# Google-analytics
google-analytics:
  id: "UA-120550008-1"

exclude: ['package.json', 'src' , 'node_modules']
